add_requires("cryptopp", "cli11", "fmt", "spdlog")
target("uecc")
    set_kind("binary")
    set_languages("c++20")
    set_warnings("error")
    add_files("src/**.cc")
    add_includedirs("inc")
    add_deps("uECC")

    add_packages("cryptopp", "cli11", "fmt", "spdlog")
